### ISSUE TITLE
[Authenticator] Authenticator should handle SessionExpiredException/SignedInException

### ISSUE THREAD

**Issue by mattcreaser** [aws-amplify/amplify-ui-android#145]
### Before creating a new issue, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-ui-android/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-ui-android/blob/main/CONTRIBUTING.md#reporting-bugsfeature-requests).

### Which UI component?

Authenticator

### Gradle script dependencies

```groovy
// Put output below this line

```

### Environment information

```
# Put output below this line


```

### Describe the bug

When Authenticator does a fetch auth session when launching it can get an `ExpiredSessionException`. If this happens it shows the Sign In screen again, but any attempts to sign in result in a `SignedInException` because there is already a user signed in.

This may be a bug in Amplify itself (to be verified if this expected), if not then this should be handled within Authenticator.

### Reproduction steps (if applicable)

1. In your cognito pool set your refresh token expiry to 60 minutes. This is under App Integration > _client_. (this is not necessary, but makes the issue much easier to reproduce)
2. Sign in with a user
3. Let the refresh token expire
4. Launch the app again, sign in screen will re-appear
5. Try to sign in again

Expected: Sign in is successful
Actual: "Something went wrong"

### Code Snippet

```java
// Put your code below this line.

```

### Log output

```
// Put your logs below this line


```

**Comment by pmellaaho** [comment]
So, the fix for this problem should have been released with Authenticator v.1.2.3
I tested this but unfortunately the sign-in is still not possible, here is the logs from Authenticator:

Moving to initial step: com.amplifyframework.ui.authenticator.enums.AuthenticatorStep$SignIn@42a7884
Moving to step: com.amplifyframework.ui.authenticator.enums.AuthenticatorStep$SignIn@42a7884
Encountered AuthException: SignedInException{message=There is already a user signed in., cause=null, recoverySuggestion=Sign out the user first before signing in again.}
Sending message: com.amplifyframework.ui.authenticator.util.UnknownErrorMessage@a46ea43

I suppose, after some debugging, that the fix was made to handleSignedIn() -method but it also needs to be fixed in handleSignInFailure()?
